name: Deploy Angular to HostGator (debug)

on:
  push:
    branches:
      - main   # ou master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build Angular
        run: npx ng build --configuration production

      - name: Debug dist folder
        run: |
          echo "===== dist ====="
          ls -la dist || true
          echo "===== dist subfolders ====="
          find dist -maxdepth 4 -type d || true
          echo "===== dist files ====="
          find dist -maxdepth 3 -type f || true

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: dist/portfolio/browser/
          server-dir: /vinivargas.com/
          dangerous-clean-slate: false
